- name: Copy forwarder upstart script
  template: src=upstart-script dest=/etc/init/logstash-forwarder.conf

- name: Create forwarder dir
  file: path={{ forwarder_install_dir }} state=directory owner={{ forwarder_user }} group={{ forwarder_user }}

- name: Copy forwarder executable
  copy: src=logstash-forwarder dest={{ forwarder_install_dir }}/logstash-forwarder

- name: Make sure executable is executable
  file: path={{ forwarder_install_dir }}/logstash-forwarder mode=0777

- name: Copy forwarder config
  template: src=logstash-forwarder.conf dest={{ forwarder_install_dir}}/logstash-forwarder.conf
  notify: [restart forwarder]

- name: Copy forwarder cert
  template: src=cert.j2 dest={{forwarder_install_dir }}/forwarder.crt

- name: Copy forwarder key
  template: src=key.j2 dest={{forwarder_install_dir }}/forwarder.key

- name: Start forwarder
  service: name=logstash-forwarder state=started
