- name: Install Beaver
  pip: name=beaver

- name: Copy beaver upstart script
  template: src=upstart-script dest=/etc/init/beaver.conf

- name: Create beaver dir
  file: path={{ beaver_install_dir }} state=directory owner={{ beaver_user }} group={{ beaver_user }}

- name: Copy beaver config
  template: src=beaver.conf dest={{ beaver_install_dir }}/beaver.conf 
  notify: [restart beaver]

- name: Ensure correct template permissions
  file: path={{ beaver_install_dir }}/beaver.conf owner={{ beaver_user }} group={{ beaver_user }}

- name: Start beaver
  service: name=beaver state=started
